apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/elk8622/unityproject.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: springapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true